config/routes.rb
Englishwithmusic::Application.routes.draw do
  root "pages#home"
  get  "about" => "pages#about"
  get "songs"  => "pages#songs"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		Panel content
	</div>
	<div class="panel-footer">
	 Panel footer
	 </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "English With Music", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="ben"><%= link_to "Home", root_path %></li>
        <li><%= link_to "Songs", songs_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Englishwithmusic</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
			<%= yield %>
		</div>
		<!-- <%= render 'layouts/footer' %> still working on footer section -->
	</body>
</html>

app/views/pages/about.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<h2><strong>About Me</strong></h2>
		<div class="row">
			<div class="col-sm-8">
				 <p>My name is Ben and I am 27 years old. I know my face looks younger! I was born in Boulder, 	Colorado and moved to New York City when I was 16 years old, in 2002.</p> 
				<p>In 2008 I moved back to Colorado for college. I graduated from the University of Colorado with a degree in Sociology in 2010.</p>
				<p>In 2012 I moved back to New York City where I worked at a music marketing company and also at a venue (casa de show) as a sound engineer. </p>
				<p>I love music, playing guitar, learning new languages and of course teaching Brazilians English!</p>
				<p>Muito obrigado for looking at my website!</p>
				<p>Ben - See more at: http://brazilenglish.weebly.com/about.html#sthash.HM8nFNbY.dpuf</p>
			</div>
			<div class="col-sm-4">
				<%= image_tag "bensitting.jpg" , style: "width:100%" %>
			</div>
		</div>
		<br>
		<br>
		<br>
		<br>
		<p><h1>Have more questions? </h1><%= link_to "Email me", "mailto:ben.fitterman@gmail.com", class: "btn btn-primary btn-lg" %></p>
	</div>
</div> <!-- panel default -->

app/views/pages/home.html.erb
  <div class="jumbotron center">
  	<h1>Aprende îngles com música!</h1>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      English With Music
    </div>
    <div class="panel-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu elit ut augue dapibus tristique eget quis ante. Vestibulum sit amet ultrices nunc, blandit eleifend diam. Duis lacinia, tortor ac lacinia tincidunt, dui tellus consectetur mi, vel aliquam quam massa ac dolor. Nullam consectetur quis sem vel scelerisque. Cras eu eros a lorem aliquam faucibus ac non ligula. Quisque nisl dui, venenatis in odio et, venenatis cursus odio. Sed in turpis at lectus rutrum volutpat sed ac massa. Suspendisse mollis pulvinar rhoncus. Praesent accumsan velit vehicula mi elementum pulvinar. Donec eleifend urna lacus, nec bibendum nunc rhoncus sit amet. Vivamus a orci nec nunc cursus viverra at eget massa.</p>
  		<p>The Best way to <%= link_to "learn", "#"%></p>
    </div>
  </div>
  <div class="row">
      <div class="col-sm-4">
        <div class="panel panel-warning">
          <div class="panel-heading">
            English With Music
          </div>
          <div class="panel-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu elit ut augue dapibus tristique eget quis ante. Vestibulum sit amet ultrices nunc, blandit eleifend diam. Duis lacinia, tortor ac lacinia tincidunt, dui tellus consectetur mi, vel aliquam quam massa ac dolor. Nullam consectetur quis sem vel scelerisque. Cras eu eros a lorem aliquam faucibus ac non ligula. Quisque nisl dui, venenatis in odio et, venenatis cursus odio. Sed in turpis at lectus rutrum volutpat sed ac massa. Suspendisse mollis pulvinar rhoncus. Praesent accumsan velit vehicula mi elementum pulvinar. Donec eleifend urna lacus, nec bibendum nunc rhoncus sit amet. Vivamus a orci nec nunc cursus viverra at eget massa.</p>
        		<p>The Best way to <%= link_to "learn", "#"%></p>
          </div>
        </div>
      </div>  <!-- column div-->
    <div class="col-sm-4">
      <div class="panel panel-danger">
        <div class="panel-heading">
          English With Music
        </div>
        <div class="panel-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu elit ut augue dapibus tristique eget quis ante. Vestibulum sit amet ultrices nunc, blandit eleifend diam. Duis lacinia, tortor ac lacinia tincidunt, dui tellus consectetur mi, vel aliquam quam massa ac dolor. Nullam consectetur quis sem vel scelerisque. Cras eu eros a lorem aliquam faucibus ac non ligula. Quisque nisl dui, venenatis in odio et, venenatis cursus odio. Sed in turpis at lectus rutrum volutpat sed ac massa. Suspendisse mollis pulvinar rhoncus. Praesent accumsan velit vehicula mi elementum pulvinar. Donec eleifend urna lacus, nec bibendum nunc rhoncus sit amet. Vivamus a orci nec nunc cursus viverra at eget massa.</p>
      		<p>The Best way to <%= link_to "learn", "#"%></p>
        </div>
      </div>
    </div> <!-- column -->  
    <div class="col-sm-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          English With Music
        </div>
        <div class="panel-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu elit ut augue dapibus tristique eget quis ante. Vestibulum sit amet ultrices nunc, blandit eleifend diam. Duis lacinia, tortor ac lacinia tincidunt, dui tellus consectetur mi, vel aliquam quam massa ac dolor. Nullam consectetur quis sem vel scelerisque. Cras eu eros a lorem aliquam faucibus ac non ligula. Quisque nisl dui, venenatis in odio et, venenatis cursus odio. Sed in turpis at lectus rutrum volutpat sed ac massa. Suspendisse mollis pulvinar rhoncus. Praesent accumsan velit vehicula mi elementum pulvinar. Donec eleifend urna lacus, nec bibendum nunc rhoncus sit amet. Vivamus a orci nec nunc cursus viverra at eget massa.</p>
      		<p>The Best way to <%= link_to "learn", "#"%></p>
        </div>
      </div>
    </div> <!-- colum -->  
  </div> <!-- row -->    